### ISSUE TITLE
Setup.cfg has a duplicate section for flake8

### ISSUE THREAD

**Issue by jasonyates** [netbox-community/cookiecutter-netbox-plugin#1]
I used the cookiecutter template to start a plugin, running `python setup.py develop `to install the plugin locally fails with the following error

`configparser.DuplicateSectionError: While reading from 'setup.cfg' [line 48]: section 'flake8' already exists`

Removing the duplicate entry for flake8 resolves the issue.

**Comment by arthanson** [comment]
Awesome! Thank you for reporting this - was still in beta so great to get these issues reported.

**Comment by jasonyates** [comment]
@arthanson I used this to build https://github.com/jasonyates/netbox-circuitmaintenance over the weekend. It worked great. I have a few other issues I can open if you are looking for additional feedback.
