### ISSUE TITLE
Include templates in MANIFEST.in

### ISSUE THREAD

**Issue by rixx** [netbox-community/cookiecutter-netbox-plugin#13]
* Date you used Cookiecutter NetBox plugin: yesterday
* Cookiecutter version used, if any: 2.1.1
* Python version, if any: 3.10

I installed a plugin generated with this cookiecutter, and got a bunch of `TemplateNotFoundError`s. The installation process was via git+https (as the plugin is not on PyPI yet). I figured out that the errors went away when you include (or recursive-include) `module_name/templates/module_name/` in `MANIFEST.in`.

I assume things worked locally because dev installs are treated differently – adding the include fixed the matter when installing the plugin. Would probably be nice to include by default. Happy to provide a PR, but really, it's just this one line:

```
recursive-include {{cookiecutter.project_slug}}/templates *.html
```

**Comment by pheus** [comment]
It seems to be fixed in rev c1d4c29beab458d5b793a63e30c561a32f469b58 (#17):

```shell
graft templates
```
